# Generated by Django 5.2.7 on 2025-10-21 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('closing_day', models.PositiveSmallIntegerField(help_text='Dia do fechamento da fatura (1-28)')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia do vencimento da fatura (1-28)')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('plataform', models.CharField(blank=True, help_text='Plataforma de investimento', max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('day_of_month', models.PositiveSmallIntegerField(help_text='1-28 (use p/ meses menores)')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use o primeiro dia do mês, ex.: 2025-10-01')),
                ('save_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'unique_together': {('month',)},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=150)),
                ('payment_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('pix', 'Pix'), ('transfer', 'Transferência')], max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('installments_count', models.PositiveSmallIntegerField(default=1)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.card')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.category')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.purchase')),
            ],
            options={
                'ordering': ['due_date', 'purchase_id', 'number'],
                'unique_together': {('purchase', 'number')},
            },
        ),
    ]
